---
- name: 'Drinks by Home Assistant state'
  hosts: localhost
  sources:
    - runejuhl.unusual_ansible.url_probe:
        urls:
        - '{{ hass_baseurl }}/api/states/person.rune'
        headers:
          Authorization: 'Bearer {{ hass_token }}'
          content-type: application/json
        delay: 5

  rules:
    - name: 'Rune is at home (or at Vue)'
      condition: |-
        (
         event.meta.source.name == 'url_probe'
         and
         event.url_probe.body.state == 'not_home'
         and
         facts.last_state != 'not_home'
        )
        or
        event.url_probe.body.state == 'vue'
      throttle:
        once_within: 5 minutes
        group_by_attributes:
        - event.meta.source.name


      actions:
      - run_job_template:
          name: make_drinks
          organization: Default
          job_args:
            extra_vars:
              drink_name: gt

      # - set_fact:
      #     fact:
      #       last_state: |-
      #         {{ event.url_probe.body.state }}
      # - debug:
      #     msg: |
      #       Last state: {{ ansible_facts.last_state|default() }}
      #       Current state: {{ event.url_probe.body.state }}
