---
- name: 'home assistant websocket presence'
  hosts: localhost
  sources:
  - hass_websocket:
      uri: 'wss://{{ hass_domain }}/api/websocket'
      access_token: '{{ hass_token }}'
      event_types:
      - state_changed

  rules:
    - name: Any event
      condition: |-
        event.payload.event.data.entity_id is regex('^binary_sensor\..+?_presence$')
        and
        event.payload.event.data.new_state.state in ['on', 'off']

      action:
        run_playbook:
          name: ./playbooks/dump_event.yml
