---
- name: http sse events
  hosts: localhost
  default_events_ttl: "2 seconds"
  match_multiple_rules: false
  sources:
  - runejuhl.unusual_ansible.http_sse:
      url: '{{ loo_roll_basename }}/events'
      event_ids:
      - binary_sensor-toilet_paper_situation_

  rules:
  - name: Detect no paper left on loo roll
    condition:
      all:
      - event.data.value

    actions:
    - print_event:
        pretty: true

    - run_job_template:
        name: loo_roll_empty
        organization: Default

    - run_job_template:
        name: send_notification
        organization: Default
        job_args:
          extra_vars:
            message: |-
              TP roll empty!
            icon: |-
              /usr/share/notify-osd/icons/Humanity/scalable/status/notification-printer-error.svg
