---
- name: mqtt events
  hosts: localhost
  sources:
    - mqtt:
        host: 192.168.1.243
        # We're only interested in events one level down from `zigbee2mqtt`
        topic: 'zigbee2mqtt/+'

  rules:
    - name: Respond to player spawn events
      condition: event.topic == "zigbee2mqtt/Basement outlet"
      action:
        run_playbook:
          name: ./playbooks/mqtt.yml
