---
- name: |-
    Make drinks
  hosts: localhost
  gather_facts: false
  tasks:

  - name: 'Bartender'
    ansible.builtin.uri:
      url: '{{ drinks_basename }}/drink/{{ drink_name }}'
      method: POST
      return_content: true
      timeout: 120
    register: response

  - debug:
      msg: |
        {{ response.content }}
